package com.cacanode.api.common.enums;

public enum LogAction {
    SETUP_COMPLETED,
    WORKSPACE_CREATED,
    WORKSPACE_ARCHIVED,
    WORKSPACE_VISIBILITY_CHANGED,
    SELF_REGISTRATION_TOGGLED,
    NOTIFICATION_CHANNEL_CHANGED,
    MEMBER_ADDED,
    MEMBER_REMOVED,
    MEMBER_ROLE_CHANGED,
    USER_INVITE,
    USER_INVITATION_RESENT,
    USER_INVITATION_CANCELLED,
    USER_INVITATION_ACCEPTED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    USER_PASSWORD_CHANGED,
    USER_PASSWORD_RESET
}
