package com.cacanode.api.common.enums;

public enum LogAction {
    USER_INVITE,
    USER_INVITATION_RESENT,
    USER_INVITATION_CANCELLED,
    USER_INVITATION_ACCEPTED,
    USER_ROLE_CHANGED,
    USER_DEACTIVATED,
    USER_REACTIVATED,
    USER_SUSPENDED_VERIFICATION_ABUSE,
    LOGIN_2FA_REQUESTED,
    LOGIN_2FA_RESEND_REQUESTED,
    LOGIN_2FA_RESEND_LIMIT_EXCEEDED,
    LOGIN_2FA_VERIFIED
}
